version: '3'
services:
  mariadb:
    image: mariadb
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "scipionyx_industrially_image_recon"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"